services:
  replica1:
    container_name: replica1
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.replica
    environment:
      REPLICA_ID: "1"
      PORT: "4001"
      PEERS: "http://replica2:4002,http://replica3:4003"
      DEV_MODE: "false"
    volumes:
      - ./replica1/src:/app/src:cached
      - ./src/frontend:/app/src/frontend:cached
      - ./data/replica1:/app/data
    ports:
      - "4001:4001"
    restart: "on-failure"
    networks:
      - raft-network

  replica2:
    container_name: replica2
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.replica
    environment:
      REPLICA_ID: "2"
      PORT: "4002"
      PEERS: "http://replica1:4001,http://replica3:4003"
      DEV_MODE: "false"
    volumes:
      - ./replica2/src:/app/src:cached
      - ./src/frontend:/app/src/frontend:cached
      - ./data/replica2:/app/data
    ports:
      - "4002:4002"
    restart: "on-failure"
    networks:
      - raft-network

  replica3:
    container_name: replica3
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.replica
    environment:
      REPLICA_ID: "3"
      PORT: "4003"
      PEERS: "http://replica1:4001,http://replica2:4002"
      DEV_MODE: "false"
    volumes:
      - ./replica3/src:/app/src:cached
      - ./src/frontend:/app/src/frontend:cached
      - ./data/replica3:/app/data
    ports:
      - "4003:4003"
    restart: "on-failure"
    networks:
      - raft-network

networks:
  raft-network:
    name: raft-network
    driver: bridge
