FROM node:20-alpine

WORKDIR /app

COPY package.json ./package-lock.json ./
COPY node_modules ./node_modules

COPY src ./src

ENV PORT=3000
EXPOSE 3000

# Use nodemon if DEV_MODE is set; otherwise run normally
CMD ["sh", "-c", "if [ \"$DEV_MODE\" = \"true\" ]; then ./node_modules/.bin/nodemon --watch src --delay 1 --exec \"npm run start:gateway\"; else npm run start:gateway; fi"]